# Generated by Django 6.0.2 on 2026-03-31 07:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringInvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=30, unique=True)),
                ('template_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('Bi-weekly', 'Bi-weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=20)),
                ('interval_count', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('next_run_date', models.DateField()),
                ('due_days', models.PositiveIntegerField(default=0)),
                ('cycle_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('auto_send', models.BooleanField(default=False)),
                ('approval_required', models.BooleanField(default=False)),
                ('email_reminder_before_due', models.BooleanField(default=False)),
                ('overdue_followup', models.BooleanField(default=False)),
                ('gst_enabled', models.BooleanField(default=False)),
                ('ledger_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_post_sales_ledger', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates', to='invoices.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
