# Generated by Django 6.0.2 on 2026-03-23 10:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('challan_date', models.DateField(default=django.utils.timezone.now)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=30, null=True)),
                ('transporter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Draft', max_length=20)),
                ('total_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_challans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-challan_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='Nos', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='DeliveryChallan.deliverychallan')),
            ],
        ),
    ]
